apiVersion: v1
kind: Service
metadata:

  name: ingress-svc

  labels:
    app: ingress-svc

spec:

  type: LoadBalancer
  loadBalancerIP: 35.224.39.104
#   loadBalancerIP: 107.178.246.164
  ports:

  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  selector:
    k8s-app: ingress-controller
