apiVersion: v1
kind: Service
metadata:

  name: ingress-controller

  labels:
    app: ingress-controller
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=mlfabric-dev-1-ingress"
spec:

  type: LoadBalancer
  loadBalancerSourceRanges:
    - 9.0.0.0/16
#  loadBalancerIP: $LOADBALANCER_IP
  #externalTrafficPolicy: Local
  # type: ClusterIP
  ports:
  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  selector:
    app: ingress-controller
