apiVersion: v1
kind: Service
metadata:

  name: ingress-controller

  labels:
    app: ingress-controller

spec:

  type: LoadBalancer
  loadBalancerIP: $LOADBALANCER_IP
  ports:
  - port:       80
    targetPort: 80
    name:       http

  - port:       443
    targetPort: 443
    name:       https

  selector:
    app: ingress-controller
